site_name: hydrus network
site_description: "A personal booru-style media tagger that can import files and tags from your hard drive and popular websites. Content can be shared with other users via user-run servers."
site_url: ''
repo_url: https://github.com/hydrusnetwork/hydrus
repo_name: hydrusnetwork/hydrus
use_directory_urls: false
nav:
  - index.md
  - Getting Started:
    - introduction.md
    - gettingStartedOverview.md
    - getting_started_installing.md
    - getting_started_files.md
    - filetypes.md
    - getting_started_importing.md
    - getting_started_tags.md
    - getting_started_searching.md
    - getting_started_more_tags.md
    - getting_started_downloading.md
    - getting_started_ratings.md
    - PTR: 
      - access_keys.md
      - PTR.md
      - petitionPractices.md
    - Next Steps:
      - adding_new_downloaders.md
      - getting_started_subscriptions.md
      - duplicates.md
  - Advanced:
    - advanced_siblings.md
    - advanced_parents.md
    - advanced_sidecars.md
    - advanced_multiple_local_file_services.md
    - advanced_duplicates_auto_resolution.md
    - advanced.md
    - reducing_lag.md
    - database_migration.md
    - database_merging.md
    - custom_assets.md
    - launch_arguments.md
    - ipfs.md
    - server.md
    - Alternate Installations:
      - docker.md
      - wine.md
      - running_from_source.md
    - Downloader Creation:
      - Introduction: downloader_intro.md
      - downloader_gugs.md
      - downloader_url_classes.md
      - Parsers:
        - Overview: downloader_parsers.md
        - Components:
          - Formulae: downloader_parsers_formulae.md
          - downloader_parsers_content_parsers.md
          - downloader_parsers_page_parsers.md
        - Walkthroughs:
          - downloader_parsers_full_example_gallery_page.md
          - downloader_parsers_full_example_file_page.md
          - downloader_parsers_full_example_api.md
      - downloader_completion.md
      - downloader_sharing.md
      - downloader_login.md
  - API: 
    - client_api.md
    - developer_api.md
  - Misc:
    - faq.md
    - privacy.md
    - contact.md
    - support.md
    - changelog.md
    - about_docs.md

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: assets/hydrus-white.svg
  favicon: assets/favicon.svg
  font: false
  language: en
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - content.tabs.link
    - navigation.top
    - search.suggest
    - content.code.annotate
    #- navigation.indexes
  icon:
    repo: fontawesome/brands/github
    
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hydrusnetwork/hydrus
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/hydrusnetwork
    - icon: fontawesome/brands/tumblr
      link: https://hydrus.tumblr.com/
    - icon: fontawesome/solid/envelope
      link: mailto:hydrus.admin@gmail.com
    - icon: fontawesome/brands/discord
      link: https://discord.gg/wPHPCUZ
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/hydrus_dev

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      separator: "_"

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets

plugins:
  - search
  - offline
