name: Release-Windows
on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
        with:
          path: hydrus
      -
        name: Extract Version Metadata
        id: meta
        run: |
          $vs = "${{ github.ref_name }}".Substring(1)
          echo "version_short=$vs" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      -
        name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          architecture: x64
      -
        name: Pip Install
        run: python3 -m pip install -r hydrus/static/build_files/windows/requirements.txt
      - 
        name: Build docs to /help
        run: mkdocs build -d help
        working-directory: hydrus
      -
        name: Download mpv-dev
        run: Invoke-WebRequest -Uri "https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-20260201-git-40d2947.7z" -OutFile "mpv-dev-x86_64.7z" -Headers @{ "User-Agent" = "LetMeIn" }
      -
        name: Process mpv-dev
        run: |
          7z x mpv-dev-x86_64.7z -ompv
          move mpv\libmpv-2.dll hydrus\mpv-2.dll
      -
        name: Download ffmpeg
        run: Invoke-WebRequest -Uri "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z" -OutFile "ffmpeg-release-full.7z"
      -
        name: Process ffmpeg
        run: |
          7z e ffmpeg-release-full.7z -ohydrus/bin "**/bin/ffmpeg.exe"
      -
        name: Build Hydrus
        run: |
          python hydrus\static\build_files\windows\file_version_info_maker.py ${{ github.ref_name }}
          move hydrus\static\build_files\windows\hydrus.spec hydrus.spec
          pyinstaller hydrus.spec
      -
        name: InnoSetup
        run: |
          move hydrus\static\build_files\windows\InnoSetup.iss InnoSetup.iss
          ISCC.exe InnoSetup.iss /DVersion=${{ github.ref_name }} /DVersionShort=${{ env.version_short }}
      -
        name: Compress Client
        run: |
          7z.exe a -tzip -mm=Deflate -mx=5 Hydrus.Network.${{ env.version_short }}.-.Windows.-.Extract.only.zip .\dist\*
      -
        name: Upload Files
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Hydrus.Network.${{ env.version_short }}.-.Windows.-.Installer.exe
            Hydrus.Network.${{ env.version_short }}.-.Windows.-.Extract.only.zip
