name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          path: hydrus
      -
        name: Setup FFMPEG
        uses: FedericoCarboni/setup-ffmpeg@v1.1.0
        id: setup_ffmpeg
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: x64
      -
        name: Pip Install
        run: python3 -m pip install -r hydrus/static/build_files/windows/requirements.txt
      - 
        name: Build docs to /help
        run: mkdocs build -d help
        working-directory: hydrus
      #-
      #  name: Cache Qt
      #  id: cache_qt
      #  uses: actions/cache@v1
      #  with:
      #    path: ../Qt
      #    key: ${{ runner.os }}-QtCache
      #-
      #  name: Install Qt
      #  uses: jurplel/install-qt-action@v2
      #  with:
      #    install-deps: true
      #    setup-python: 'false'
      #    modules: qtcharts qtwidgets qtgui qtcore
      #    cached: ${{ steps.cache_qt.outputs.cache-hit }}
      -
        name: Download mpv-dev
        uses: carlosperate/download-file-action@v1.1.1
        id: download_mpv
        with:
            file-url: 'https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-20220501-git-9ffaa6b.7z'
            file-name: 'mpv-dev-x86_64.7z'
            location: '.'
      -
        name: Process mpv-dev
        run: |
          7z x ${{ steps.download_mpv.outputs.file-path }}
          move mpv-2.dll hydrus\
      -
        name: Build Hydrus
        run: |
          move ${{ steps.setup_ffmpeg.outputs.ffmpeg-path }} hydrus\bin\
          move hydrus\static\build_files\windows\sqlite3.dll hydrus\
          move hydrus\static\build_files\windows\sqlite3.exe hydrus\db
          move hydrus\static\build_files\windows\client-win.spec client-win.spec
          move hydrus\static\build_files\windows\server-win.spec server-win.spec
          pyinstaller server-win.spec
          pyinstaller client-win.spec
          dir -r
      -
        # yo pretty sure we'll need to install this manually once we are on windows server 2022
        # https://github.com/actions/virtual-environments/issues/4856
        name: InnoSetup
        run: |
          move hydrus\static\build_files\windows\InnoSetup.iss InnoSetup.iss
          ISCC.exe InnoSetup.iss /DVersion=${{ github.ref_name }}
      -
        name: Compress Client
        run: |
          cd .\dist
          7z.exe a -tzip -mm=Deflate -mx=5 ..\Windows-Extract.zip 'Hydrus Network'
          cd ..
      -
        name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Install
          path: dist\HydrusInstaller.exe
          if-no-files-found: error
          retention-days: 2
      -
        name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Extract
          path: Windows-Extract.zip
          if-no-files-found: error
          retention-days: 2

  create-release:
    name: Create Release Entry
    runs-on: ubuntu-20.04
    needs: [build-windows]
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      - 
        name: Get All Artifacts
        uses: actions/download-artifact@v3
      - 
        name: Extract version metadata
        id: meta
        run: |
          echo "version=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "version_short=${GITHUB_REF##*/v}" >> $GITHUB_ENV
      - 
        name: Rename Files
        run: |
          mkdir ubuntu windows
          mv Windows-Install/HydrusInstaller.exe    Hydrus.Network.${{ env.version_short }}.-.Windows.-.Installer.exe
          mv Windows-Extract/Windows-Extract.zip  Hydrus.Network.${{ env.version_short }}.-.Windows.-.Extract.only.zip
      - 
        name: Release new
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Hydrus.Network.${{ env.version_short }}.-.Windows.-.Installer.exe
            Hydrus.Network.${{ env.version_short }}.-.Windows.-.Extract.only.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
